import { Post, PostService } from "cms-alganews-sdk";
import type { GetServerSideProps, NextPage } from "next";
import Head from "next/head";
import React from "react";
import { FeaturedPost } from "../components/FeaturedPost";

interface HomeProps {
  posts: Post.Paginated;
}

const Home = ({ posts }: HomeProps) => {
  return (
    <div>
      <Head>
        <title>Alganews</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {posts.content && <FeaturedPost postSummary={posts.content[0]} />}
    </div>
  );
};

export default Home;

export const getServerSideProps: GetServerSideProps = async () => {
  const posts = await PostService.getAllPosts({ page: 0 });
  return {
    props: { posts },
  };
};
